name: "Flatpak"

on:
  push:
    # Don't run CI for tags; there's always a branch for the tag as well so
    # there's no point in testing it separately
    tags_ignore: "*"
    # Only run this workflow on main because it takes a while, and the "lint"
    # workflow should catch most things.
    branches: [main]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
  pull_request:

jobs:
  devel:
    name: "Build Devel flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: de.swsnr.app.Supervisor.Devel.flatpak
          manifest-path: de.swsnr.app.Supervisor.Devel.yaml
          cache-key: flatpak-builder-${{ github.sha }}
