name: "Flatpak"

on:
  push:
    # Don't run CI for tags; there's always a branch for the tag as well so
    # there's no point in testing it separately
    tags_ignore: "*"
  pull_request:

jobs:
  devel:
    name: "Build Devel flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: de.swsnr.app.Argus.Devel.flatpak
          manifest-path: de.swsnr.app.Argus.Devel.yaml
          cache-key: flatpak-builder-${{ github.sha }}
